[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.12.x"
serde = {version = "1.x", features = ["derive"]}
serde_json = "1.x"
rug = "1.x"
pretty_env_logger = "0.2.3" # DELETE SOON

[profile.release]
incremental = true
debug = 0
lto = true
codegen-units = 1

