[package]
name = "api"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.0.0-rc"
serde = {version = "1.x", features = ["derive"]}
serde_json = "1.x"
rug = "1.x"
tokio = { version = "1.17.x", features = ["full"] }

[profile.release]
incremental = false
debug = 0
lto = true
codegen-units = 1

[profile.dev]
opt-level = 1
debug = true
incremental = true
