timeout: 1800s
steps:
  # download last builded image to cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c',
      'docker pull
              ${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
              || exit 0' ]
  # push latest rust and distroless images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c',
      'docker pull docker.io/rust:latest && 
              docker pull gcr.io/distroless/static:latest' ]
  # Build Output image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t',
            '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}',
            '-t',
            '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest',
            '--cache-from',
            '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest',
            '.' ]
  # Push Image with all tags
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',
            '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',
            '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest' ]
images:
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'
  - '${_LOCATION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'