timeout: 2400s
steps:
  # download last built image to cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c',
      'docker pull
              us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
              || exit 0' ]
  # push latest rust and distroless images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: [ '-c',
      'docker pull docker.io/rust:latest && 
              docker pull gcr.io/distroless/cc:latest' ]
  # Build Output image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '-t',
            'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}',
            '-t',
            'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest',
            '--cache-from',
            'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest',
            '.' ]
  # Push Image with all tags
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',
            '$us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push',
            'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest' ]
  # update gke

  ## Long Primes
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/autoscaler.yaml
      - --filename=kubernetes/deployment.yaml
      - --filename=kubernetes/service.yaml
      - --filename=kubernetes/long-configMap.yaml
#      - --filename=kubernetes/http2-service.yaml
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
      - --location=us-central1
      - --cluster=central1-long-primes

  ## Short Primes
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=kubernetes/autoscaler.yaml
      - --filename=kubernetes/deployment.yaml
      - --filename=kubernetes/service.yaml
      - --filename=kubernetes/short-configMap.yaml
#      - --filename=short-kubernetes/http2-service.yaml
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest
      - --location=us-central1
      - --cluster=central1-small-primes
# Deployment images
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${COMMIT_SHA}'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:latest'