timeout: 2400s
steps:
  # Build Output image
  - name: 'gcr.io/kaniko-project/executor:latest'
    args: [ '--destination=us-docker.pkg.dev/$PROJECT_ID/us/$REPO_NAME:latest',
            '--destination=us-docker.pkg.dev/$PROJECT_ID/us/$REPO_NAME:${SHORT_SHA}',
            '--cache=true',
            '--cache-ttl=12h'
    ]