timeout: 1200s
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/primesnumbers/worker', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/primesnumbers/worker']
