apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: worker-scaler-autoscaling
  labels:
    app: workerV1
spec:
  scaleTargetRef:
    kind: Deployment
    name: workerV1
    apiVersion: apps/v1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60